import type { EventType, Lang } from './events';

// Copy presets per event type (PRD F9). BM is the default; EN mirrors it.
export const eventCopy: Record<EventType, Record<Lang, { title: string; intro: string }>> = {
  kahwin: {
    bm: { title: 'Walimatul Urus', intro: 'Dengan penuh kesyukuran, kami menjemput anda ke majlis perkahwinan' },
    en: { title: 'Wedding Reception', intro: 'With gratitude, we invite you to the wedding of' },
  },
  aqiqah: {
    bm: { title: 'Majlis Aqiqah', intro: 'Kami menjemput anda ke majlis aqiqah dan cukur jambul' },
    en: { title: 'Aqiqah', intro: 'We invite you to the aqiqah of' },
  },
  rumah_terbuka: {
    bm: { title: 'Rumah Terbuka', intro: 'Jemput datang beraya bersama' },
    en: { title: 'Open House', intro: 'Please join us for an open house with' },
  },
  tahlil: {
    bm: { title: 'Majlis Tahlil', intro: 'Kami menjemput anda ke majlis tahlil dan doa selamat' },
    en: { title: 'Tahlil', intro: 'We invite you to a tahlil and prayer gathering' },
  },
  hari_jadi: {
    bm: { title: 'Majlis Hari Jadi', intro: 'Jom raikan hari jadi' },
    en: { title: 'Birthday', intro: 'Come celebrate the birthday of' },
  },
};

export const ui = {
  bm: {
    when: 'Tarikh & masa',
    where: 'Tempat',
    rsvpTitle: 'Adakah anda akan hadir?',
    rsvpBy: (d: string) => `Sila jawab sebelum ${d}`,
    yes: 'Hadir',
    no: 'Tak dapat hadir',
    name: 'Nama',
    phone: 'No. telefon (pilihan)',
    phoneWhy: 'Hanya tuan rumah nampak. Untuk peringatan majlis sahaja.',
    pax: 'Bilangan orang',
    doa: 'Doa atau ucapan (pilihan)',
    send: 'Hantar jawapan',
    saving: 'Menyimpan…',
    saved: 'Disimpan',
    retry: 'Tiada sambungan. Mencuba lagi…',
    failed: 'Tak berjaya disimpan. Cuba sekali lagi.',
    nameRequired: 'Sila isi nama anda.',
    yourAnswers: 'Jawapan dari telefon ini',
    edit: 'Ubah',
    answerForOther: 'Jawab untuk orang lain',
    thanksYes: 'Terima kasih! Jumpa di majlis.',
    thanksNo: 'Terima kasih atas doa anda.',
    ownEvent: 'Ada majlis sendiri?',
    ownEventCta: 'Buat kad percuma',
    countdown: 'Lagi',
    days: 'hari',
    music: 'Main muzik',
    pause: 'Henti muzik',
    safe: 'Pautan web · tiada muat turun',
    safeMore: 'Cara semak pautan',
    madeWith: 'Dibuat dengan Hadir',
    makeYours: 'Buat kad anda',
    calendar: 'Simpan ke kalendar',
    people: 'orang',
  },
  en: {
    when: 'Date & time',
    where: 'Venue',
    rsvpTitle: 'Will you attend?',
    rsvpBy: (d: string) => `Please reply by ${d}`,
    yes: 'Attending',
    no: "Can't make it",
    name: 'Name',
    phone: 'Phone (optional)',
    phoneWhy: 'Only the host sees this. Used for event reminders only.',
    pax: 'Number of people',
    doa: 'Wishes (optional)',
    send: 'Send reply',
    saving: 'Saving…',
    saved: 'Saved',
    retry: 'No connection. Retrying…',
    failed: "Couldn't save. Please try again.",
    nameRequired: 'Please enter your name.',
    yourAnswers: 'Replies from this phone',
    edit: 'Edit',
    answerForOther: 'Reply for someone else',
    thanksYes: 'Thank you! See you there.',
    thanksNo: 'Thank you for your wishes.',
    ownEvent: 'Hosting an event?',
    ownEventCta: 'Make a free invite',
    countdown: 'In',
    days: 'days',
    music: 'Play music',
    pause: 'Pause music',
    safe: 'Web link · no downloads',
    safeMore: 'How to check a link',
    madeWith: 'Made with Hadir',
    makeYours: 'Make yours',
    calendar: 'Add to calendar',
    people: 'people',
  },
} as const;
