// Concierge-phase events are hand-made JSON files in src/data/events.
// They move to the `events` table in Neon once the editor ships (PRD F1/F2).

export type EventType = 'kahwin' | 'aqiqah' | 'rumah_terbuka' | 'tahlil' | 'hari_jadi';
export type Lang = 'bm' | 'en';

export interface HadirEvent {
  slug: string;
  type: EventType;
  lang: Lang;
  /** Shown large on the cover, e.g. "Sofea & Adam". */
  hostNames: string;
  /** Optional line above the names, e.g. the parents who are hosting. */
  hostedBy?: string;
  /** ISO 8601 with offset, e.g. 2026-12-12T11:00:00+08:00 */
  startsAt: string;
  endsAt: string;
  venue: { name: string; address: string; lat: number; lng: number };
  /** Last day to RSVP, YYYY-MM-DD. */
  rsvpBy?: string;
  /** Upper bound for the people stepper on an open (un-named) RSVP. */
  maxPax: number;
  /** Optional free-text note under the details (dress code, parking). */
  note?: string;
  /** Optional audio file in /public. Never autoplays. */
  musicUrl?: string;
  /** sha256 hex of the host's dashboard key. Generated by `npm run new-event`. */
  hostKeyHash: string;
}

const files = import.meta.glob<HadirEvent>('../data/events/*.json', { eager: true, import: 'default' });

export const events: HadirEvent[] = Object.values(files);

export function getEvent(slug: string): HadirEvent | undefined {
  return events.find((e) => e.slug === slug);
}

const TZ = 'Asia/Kuala_Lumpur';

export function formatDate(iso: string, lang: Lang): string {
  return new Intl.DateTimeFormat(lang === 'bm' ? 'ms-MY' : 'en-MY', {
    weekday: 'long', day: 'numeric', month: 'long', year: 'numeric', timeZone: TZ,
  }).format(new Date(iso));
}

export function formatTime(iso: string, lang: Lang): string {
  return new Intl.DateTimeFormat(lang === 'bm' ? 'ms-MY' : 'en-MY', {
    hour: 'numeric', minute: '2-digit', hour12: true, timeZone: TZ,
  }).format(new Date(iso));
}

export function mapsLinks(e: HadirEvent) {
  const { lat, lng } = e.venue;
  return {
    waze: `https://waze.com/ul?ll=${lat},${lng}&navigate=yes`,
    google: `https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}`,
  };
}

/** Google Calendar template URL: a link, not a file, so it keeps the "no downloads" promise. */
export function googleCalendarUrl(e: HadirEvent, title: string): string {
  const fmt = (iso: string) => new Date(iso).toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, '');
  const params = new URLSearchParams({
    action: 'TEMPLATE',
    text: title,
    dates: `${fmt(e.startsAt)}/${fmt(e.endsAt)}`,
    location: `${e.venue.name}, ${e.venue.address}`,
    details: `https://hadir.my/${e.slug}`,
  });
  return `https://calendar.google.com/calendar/render?${params}`;
}
